name:                exercises
version:             0.1.0.0
github:              "githubuser/exercises"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  exercises-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercises
    - hspec
    - QuickCheck
